import { DarkTheme, DefaultTheme, type Theme } from "@react-navigation/native";

export const THEME = {
  light: {
    background: "hsl(0 0% 99%)",
    foreground: "hsl(0 0% 6%)",
    card: "hsl(0 0% 100%)",
    cardForeground: "hsl(0 0% 6%)",
    popover: "hsl(0 0% 100%)",
    popoverForeground: "hsl(0 0% 6%)",
    primary: "hsl(0 0% 6%)",
    primaryForeground: "hsl(0 0% 98%)",
    secondary: "hsl(0 0% 96%)",
    secondaryForeground: "hsl(0 0% 12%)",
    muted: "hsl(0 0% 96%)",
    mutedForeground: "hsl(0 0% 40%)",
    accent: "hsl(0 0% 95%)",
    accentForeground: "hsl(0 0% 10%)",
    destructive: "hsl(0 72% 51%)",
    border: "hsl(0 0% 89%)",
    input: "hsl(0 0% 89%)",
    ring: "hsl(0 0% 64%)",
    radius: "1rem",
    chart1: "hsl(12 76% 61%)",
    chart2: "hsl(173 58% 39%)",
    chart3: "hsl(197 37% 24%)",
    chart4: "hsl(43 74% 66%)",
    chart5: "hsl(27 87% 67%)",
  },
  dark: {
    background: "hsl(0 0% 4%)",
    foreground: "hsl(0 0% 96%)",
    card: "hsl(0 0% 6%)",
    cardForeground: "hsl(0 0% 96%)",
    popover: "hsl(0 0% 6%)",
    popoverForeground: "hsl(0 0% 96%)",
    primary: "hsl(0 0% 96%)",
    primaryForeground: "hsl(0 0% 7%)",
    secondary: "hsl(0 0% 11%)",
    secondaryForeground: "hsl(0 0% 96%)",
    muted: "hsl(0 0% 10%)",
    mutedForeground: "hsl(0 0% 65%)",
    accent: "hsl(0 0% 12%)",
    accentForeground: "hsl(0 0% 96%)",
    destructive: "hsl(0 68% 58%)",
    border: "hsl(0 0% 14%)",
    input: "hsl(0 0% 14%)",
    ring: "hsl(0 0% 40%)",
    radius: "1rem",
    chart1: "hsl(220 70% 50%)",
    chart2: "hsl(160 60% 45%)",
    chart3: "hsl(30 80% 55%)",
    chart4: "hsl(280 65% 60%)",
    chart5: "hsl(340 75% 55%)",
  },
};

export const NAV_THEME: Record<"light" | "dark", Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
